spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ddz_dev
    username: ddz_dev
    password: ddz_dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.yourco.ddz: DEBUG
